### PR TITLE
Fix for issue #54.

### PR DESCRIPTION
**Pull request by t-denis**

### CODE REVIEW

**Comment by t-denis** [comment]
Not fixed really. I'll provide another fix.

**Comment by t-denis** [comment]
No, looks fine. Reopened the request.

**Comment by t-denis** [comment]
Although no more exceptions thrown during the serialization, the result is wrong for some cases. Field access is serialized instead of the actual value (constant).

**Comment by t-denis** [comment]
Not sure, what is the expected behavior.
For instance field - serialization-time values are used. For static fields (except the private static) - execution time values.
For the private static fields the serialization-time values are used.
Is this an expected behavior?
Please see unit tests for details.

**Comment by t-denis** [comment]
Maybe it would be nice to have an option for user to specify, how member access expression should be serialized:
1. Get the value on serialization time and store the value
2. Serialize the member access itself

**Comment by esskar** [comment]
Your tests for internals still fail!

**Comment by t-denis** [comment]
Just re-downloaded the latest commit 8d6ee4ab2d15c4cbcfd44665806feffedb9daf51 and pressed Test > Run > All tests. Everything looks green except the yellow ignored ThrowsStackOverflowException https://github.com/t-denis/Serialize.Linq/blob/master/src/Serialize.Linq.Tests/Issues/Issue43.cs
Can you provide more info - on what platform tests fail?
And how to run these unit tests for different platforms: SL, WP?
Thanks.

**Pull request closed without merging**
